<#
  Title: Secure RDP + Tailscale Setup (2025 Version)
  Author: ChatGPT (for Hitesh)
  Works On: Windows 10 / 11 / Server 2019+ (Admin required)
  Purpose: Enables RDP, creates secure user, installs & connects Tailscale
#>

Write-Host "`n=== Starting Secure RDP + Tailscale Setup ===`n"

# 1️⃣ Enable Remote Desktop
Write-Host "🔧 Enabling Remote Desktop..."
Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
    -Name "fDenyTSConnections" -Value 0 -Force
netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
Write-Host "✅ RDP enabled successfully.`n"

# 2️⃣ Create Secure RDP User
Write-Host "👤 Creating RDP User with strong password..."

Add-Type -AssemblyName System.Security

$charset = @{
    upper = [char[]](65..90)
    lower = [char[]](97..122)
    num   = [char[]](48..57)
    sym   = ([char[]](33..47) + [char[]](58..64) + [char[]](91..96) + [char[]](123..126))
}

$pwd = -join ((($charset.upper + $charset.lower + $charset.num + $charset.sym) | Get-Random -Count 14))
$securePwd = ConvertTo-SecureString $pwd -AsPlainText -Force
$user = "RDPUser"

if (-not (Get-LocalUser -Name $user -ErrorAction SilentlyContinue)) {
    New-LocalUser -Name $user -Password $securePwd -AccountNeverExpires
    Add-LocalGroupMember -Group "Administrators" -Member $user
    Add-LocalGroupMember -Group "Remote Desktop Users" -Member $user
    Write-Host "✅ User '$user' created successfully."
} else {
    Write-Host "ℹ User '$user' already exists."
}

Write-Host "Username: $user"
Write-Host "Password: $pwd`n"

# 3️⃣ Install Tailscale (latest stable)
Write-Host "🌐 Installing Tailscale..."
$tailscaleUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
$tempPath = "$env:TEMP\tailscale.msi"
Invoke-WebRequest -Uri $tailscaleUrl -OutFile $tempPath -UseBasicParsing
Start-Process msiexec.exe -ArgumentList "/i "$tempPath" /quiet /norestart" -Wait
Remove-Item $tempPath -Force
Write-Host "✅ Tailscale installed.`n"

# 4️⃣ Sign in to Tailscale
Write-Host "🔑 Signing in to Tailscale..."
& "$env:ProgramFiles\Tailscale\tailscale.exe" up

Write-Host "`n👉 Open the link shown above in your browser to log in."
Write-Host "Once logged in, you’ll see your system in your Tailscale Admin Console."
Write-Host "`nAfter that, run this to check your IP:"
Write-Host "  tailscale ip -4"
Write-Host "`nUse that IP to connect via RDP (mstsc).`n"

# 5️⃣ Final Output
Write-Host "============================"
Write-Host "✅ Setup Complete!"
Write-Host "RDP Username : $user"
Write-Host "RDP Password : $pwd"
Write-Host "Check Tailscale IP : tailscale ip -4"
Write-Host "============================`n"

